spring:
  # default profile settings
  profiles:
    active: local

  # 용량 제한 늘리기
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

# log
logging:
  level:
    root: INFO

# s3
cloud:
  aws:
    s3:
      bucket: ${aws.s3.bucket}
      path:
        location: location
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${aws.s3.access.key}
      secretKey: ${aws.s3.secret.key}

# 로그인 jwt
jwt:
  secret: ${jwt.secret}
  accessExpirationTime: ${jwt.expiration}
  refreshExpirationTime: ${jwt.refresh.expiration}

# fcm
fcm:
  project-id: ${FCM_PROJECT_ID}
  key-content: ${FIREBASE_KEY_CONTENT}

# 문자 발송 api key
coolsms:
  api-key: ${COOLSMS_API_KEY}
  api-secret: ${COOLSMS_API_SECRET}
  owner-phone-number: ${COOLSMS_PHONE_NUMBER}

aes:
  phone-number: ${AES_PHONE_NUMBER_KEY}

# swagger
springdoc:
  swagger-ui:
    path: /swagger
  cache:
    disabled: true
  use-fqn: true


---

# local profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${local.db.url}
    username: ${local.db.username}
    password: ${local.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 100

---

# develop profile
spring:
  config:
    activate:
      on-profile: develop
  datasource:
    url: ${aws.db.url}
    username: ${aws.db.username}
    password: ${aws.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        #        format_sql: true
        #        show_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 100
